version: "2.2"
services:
    prometheus:
      image: prom/prometheus:latest
      container_name: monitoring_prometheus
      restart: unless-stopped
      volumes:
        - ./data/prometheus/config:/etc/prometheus/
        - ./data/prometheus/data:/prometheus
      command:
        - '-config.file=/etc/prometheus/prometheus.yml'
        - '-storage.local.path=/prometheus'
        - '-alertmanager.url=http://alertmanager:9093'
      expose:
        - 9090
      ports:
        - 9090:9090
      links:
        - node-exporter:node-exporter
    node-exporter:
      image: prom/node-exporter:latest
      container_name: monitoring_node_exporter
      restart: unless-stopped
      expose:
        - 9100

    grafana:
      image: grafana/grafana:latest
      container_name: monitoring_grafana
      restart: unless-stopped
      links:
        - prometheus:prometheus
      volumes:
        - ./data/grafana:/var/lib/grafana
