version: "3"
services:
    prometheus:
      image: prom/prometheus:latest
      container_name: monitoring_prometheus
      restart: unless-stopped
      volumes:
        - ./prometheus/:/etc/prometheus/
        - prometheus_data:/prometheus
      command:
        - '--config.file=/etc/prometheus/prometheus.yml'
        - '--storage.tsdb.path=/prometheus'
        - '--web.console.libraries=/usr/share/prometheus/console_libraries'
        - '--web.console.templates=/usr/share/prometheus/consoles'
      expose:
        - 9090
      ports:
        - 9090:9090
      links:
        - node-exporter:node-exporter
    node-exporter:
      image: prom/node-exporter:latest
      container_name: monitoring_node_exporter
      restart: unless-stopped
      expose:
        - 9100

    grafana:
      image: grafana/grafana:latest
      container_name: monitoring_grafana
      restart: unless-stopped
      links:
        - prometheus:prometheus
